version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "8011:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: keko
      PASSWORD: keko
      LOCATION: /zotero
    volumes:
      - /var/www/zotero:/var/lib/dav
    expose:
      - "8011"
      - "80"
